### ISSUE TITLE
Portal view: issue with background

### ISSUE THREAD

**Issue by johnd0e** [McBen/ingress-intel-total-conversion#3]
In portal info view background should be opaque.
But after some of the updates it's transparent.
The issue appears when changing default map (CartoDB) to some other (e.g. Google).

**Comment by McBen** [comment]
Original iitc background is transparent ( rgba(8, 48, 78, 0.9); )

**Comment by johnd0e** [comment]
I was specific enough.
1. The background is not _slightly_ transparent, it is _completely_ transparent like a glass.
2. As it turned out, I've accidentally toggled "mobile device toolbar".
  So the issue is specific to mobile version.


![image](https://user-images.githubusercontent.com/1838643/49650352-8d42aa80-fa34-11e8-97c3-7f44383ffe4c.png)
